
# we can pass values to the ansible list variable and variable in the yaml file  with different webserers

all:
  children:
    webservers:
      hosts:
        172.31.41.115: 
          package_name: apache2
          php_module_list:
            - php
            - libapache2-mod-php
            - php-mysql
            - php-cli
        172.31.47.60:
          package_name: apache2  
          php_module_list:
            - php
            - libapache2-mod-php
            - php-mysql
            - php-cli
