# Install httpd and php on centos/redhat 
# sudo yum update
# sudo yum install httpd
# sudo systemctl start httpd.service
# sudo yum install php php-cli
# sudo vi /var/www/html/info.php
# <?php
# phpinfo();
# ?>
# sudo systemctl restart httpd

#initial playbook 

- hosts: all
  become: yes
  tasks:
    - name: update and install httpd
      yum:
       name: httpd
       state: present
       update_cache: yes
    - name: restart httpd server
      service:
        name: httpd
        enabled: yes
        state: restarted 
    - name: install php
      yum:
       name: php
       state: present
       update_cache: yes  
    - name: install php-mysql
      yum:
        name: php-mysql
        state: present
        update_cache: yes
    - name: restart httpd server
      service:
        name: httpd
        enabled: yes 
        state: restarted    

 # optimized the above playbook by adding handlers

- hosts: all
  become: yes
  tasks:
    - name: update and install httpd
      yum:
       name: httpd
       state: present
       update_cache: yes
      nofify: 
        name:  restart httpd server
    - name: install php
      yum:
       name: php
       state: present
       update_cache: yes  
    - name: install php-mysql
      yum:
        name: php-mysql
        state: present
        update_cache: yes
      nofify: 
        name:  restart httpd server  
  handlers:    
    - name: restart httpd server
      service:
        name: httpd
        enabled: yes
        state: restarted     



        




